# - name: installing packages for python env
#   become: true
#   apt:
#     name:
#       - python3-pip
#     update_cache: yes

# - name: Creates directory
#   file:
#     path: /home/nabajyotimodak/basic-http-server
#     state: directory

# - name: install apache2
#   become: true
#   apt: name=apache2 update_cache=yes state=latest

- name: remove python3-pip package
  become: true
  apt:
    name: python3-pip
    state: absent

- name: remove apache2 package
  become: true
  apt:
    name: apache2
    state: absent
    autoremove: yes

- name: remove apache2-bin package
  become: true
  apt:
    name: apache2-bin
    state: absent
    autoremove: yes

- name: remove apache2-data package
  become: true
  apt:
    name: apache2-data
    state: absent
    autoremove: yes

- name: remove apache2-utils package
  become: true
  apt:
    name: apache2-utils
    state: absent
    autoremove: yes